apiVersion: apps/v1
kind: Deployment
metadata:
  name: vre-home
  namespace: utility
  labels:
    app: vre-home
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vre-home
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: vre-home
    spec:
      containers:
        - name: vre-home
          image: registry-gitlab.indocresearch.org/charite/frontend_vre_home:<VERSION>
          ports:
            - containerPort: 80
          env:
            - name: env
              value: "dev"
            - name: REACT_APP_ENV
              value: "dev"
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              readOnly: true
              name: nginx-conf-vre-home
      nodeSelector:
        namespace: utility
      volumes:
        - name: nginx-conf-vre-home
          configMap:
            name: nginx-conf-vre-home
            items:
              - key: vre-home.conf
                path: vre-home.conf
---
apiVersion: v1
kind: Service
metadata:
  name: vre-home
  namespace: utility
  labels:
    app: vre-home
spec:
  ports:
    - name: vre-home
      port: 80
      targetPort: 80
      nodePort:
  selector:
    app: vre-home
  type: LoadBalancer
